### ISSUE TITLE
no_italic = false/true has no effect

### ISSUE THREAD

**Issue by RolfSievert** [RedsXDD/neopywal.nvim#4]
First of all, thanks for this plugin!

It seems that the no_italic option has no effect.
I have put this in my config:
```lua
require("neopywal").setup({
    no_italic = true
})
```
If I do a live reload of my nvim config, italics disappear (regardless of what `no_italic` is set too). If I reload again a few times when it's `false`, italics is turned on again.

Please let me know if you need any more info.

**Comment by RolfSievert** [comment]
Oops, might be an issue from my side. I put the `colorscheme neopywal` in my `.vimrc` while having the lua setup code as well. Seems that the setup didn't run before setting the colorscheme and that gave inconsistent italics.

Solved with this config
```lua
local neopywal = require("neopywal")

neopywal.setup({
    no_italic = true
})

vim.cmd.colorscheme("neopywal")
```

**Comment by RedsXDD** [comment]
Yes, make sure the `setup()` function with your options is loaded `before` you apply the colorscheme with `:colorscheme neopywal`, otherwise the plugin will load with the default set of options.

If things seem to work for you now i will close this issue.
